#!/bin/sh
# After luci-app-mosdns has created /etc/config/mosdns, enable generated
# custom yaml and default dual-WAN DNS rows.

[ -f /etc/config/mosdns ] || exit 0

uci -q set mosdns.config.configfile='/etc/mosdns/config_custom.yaml'
uci -q set mosdns.config.listen_port='5335'
uci -q set mosdns.config.listen_port_api='9091'
uci -q set mosdns.config.prefer_ipv4='1'
uci -q set mosdns.config.cache_size='20000'
uci -q set mosdns.config.lazy_cache_ttl='86400'
uci -q set mosdns.config.stats_capacity='2000'

if ! uci -q get mosdns.@wan[0] >/dev/null; then
	uci add mosdns wan
	uci set mosdns.@wan[-1].network='wan1'
	uci set mosdns.@wan[-1].bind_device='1'
	uci add_list mosdns.@wan[-1].local_dns='223.5.5.5'
	uci add_list mosdns.@wan[-1].local_dns='223.6.6.6'
	uci add_list mosdns.@wan[-1].remote_dns='8.8.8.8'
	uci add_list mosdns.@wan[-1].remote_dns='1.1.1.1'

	uci add mosdns wan
	uci set mosdns.@wan[-1].network='wan2'
	uci set mosdns.@wan[-1].bind_device='1'
	uci add_list mosdns.@wan[-1].local_dns='119.29.29.29'
	uci add_list mosdns.@wan[-1].local_dns='1.12.12.12'
	uci add_list mosdns.@wan[-1].remote_dns='1.1.1.1'
	uci add_list mosdns.@wan[-1].remote_dns='8.8.8.8'
fi

uci commit mosdns
[ -x /usr/share/mosdns/gen-config-custom ] && /usr/share/mosdns/gen-config-custom
exit 0
