#!/bin/sh /etc/rc.common
START=99
USE_PROCD=0

start() {
	[ "$(uci -q get isp-ip.main.auto)" = "1" ] || return 0
	[ -x /usr/libexec/isp-ip-update ] || return 0
	/bin/sh /usr/libexec/isp-ip-update >/dev/null 2>&1 &
}
